apiVersion: v1
kind: Service
metadata:
  name: pizza-app-backend-service
  labels:
    app: pizza-app-service
    kind: backend-service
  namespace: pizza-app
spec:
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: pizza-app-pod
    kind: backend
