apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: pizza-app-deployment
    kind: backend
  namespace: pizza-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza-app-pod
      kind: backend
  template:
    metadata:
      name: nodejs-pod
      labels:
        app: pizza-app-pod
        kind: backend
    spec:
      containers:
        - env:
            - name: MONGO_URL
              value: pizza-app-database-service
          image: backend
          name: backend
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always
