apiVersion: v1
kind: Service
metadata:
  name: pizza-app-frontend-service
  labels:
    app: pizza-app-service
    kind: frontend-service
  namespace: pizza-app
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: pizza-app-pod
    kind: frontend
