apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: pizza-app-deployment
    kind: database
  namespace: pizza-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza-app-pod
      kind: database
  template:
    metadata:
      name: mongo-pod
      labels:
        app: pizza-app-pod
        kind: database
    spec:
      containers:
        - image: mongo
          name: mongo
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "250m"
              memory: "512Mi"
      restartPolicy: Always
